version: "3.7"

services:
  
  app_proxy:
    environment:
      APP_HOST:
      APP_PORT:

  bridge-kas:
    container_name: bridge-kas
    image: elldee/bridge:latest
    restart: unless-stopped
    ports:
      - "5555:5555/tcp"
      - "2114:2114/tcp"
    volumes:
      - "config:/app/config"

volumes:
  config:
