version: "3.7"

services:

  bridge:
    container_name: bridge
    image: elldee/bridge:latest
    restart: unless-stopped
    user: "0"
    command:
      - '-stats=false'
      - '-kaspa=host.docker.internal:16110'
    ports:
      - 5555:5555
      - 2114:2114
    extra_hosts:
      - host.docker.internal:host-gateway