version: "3.7"

services:
  bridge-test:
    build:
      context: ./elldeeone-bridge-test
      dockerfile: Dockerfile
      no_cache: true
    container_name: bridge-test
    restart: unless-stopped
    user: "0"
    command:
      - '-stats=false'
      - '-kaspa=host.docker.internal:16110'
    ports:
      - 5555:5555
      - 2114:2114
    extra_hosts:
      - host.docker.internal:host-gateway