version: "3.9"
services:
  ks_bridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ks_bridge
    restart: unless-stopped
    ports:
      - "5555:5555"
      - "2114:2114"
    extra_hosts:
      - "host.docker.internal:host-gateway"
