version: "3.7"
services:
  bridge:
    build:
      context: .
      dockerfile: Dockerfile  # Ensure this points to your Dockerfile
    container_name: bridge-test
    restart: unless-stopped
    ports:
      - "5555:5555"
      - "2114:2114"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "config:/app/config"

volumes:
  config:
