version: "3.7"

services:
  grafana:
    image: elldee/grafana:latest
    container_name: ks_grafana
    restart: unless-stopped
    user: "0"
    volumes:
      - ./grafana/grafana:/var/lib/grafana
#    env_file:
#      - ./docker/grafana.env
    ports:
      - 3000:3000
    extra_hosts:
      - host.docker.internal:host-gateway