version: "3.7"

services:
  grafana:
    container_name: ks_grafana
    image: elldee/grafana:latest
    restart: unless-stopped
    user: "0"
    environment:
      - GF_PATHS_DATA=/grafana/buildfiles
    ports:
      - "3000:3000/tcp"
    extra_hosts:
      - "host.docker.internal:host-gateway"