version: "3.8"
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: ks_prom
    restart: unless-stopped
    volumes:
      - "prometheus_data:/prometheus"
      - "./docker/prometheus.yml:/etc/prometheus/docker/prometheus.yml"
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  prometheus_data: {}
