version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: elldeeone-kas-stratum-bridge_1
      APP_PORT: 3000

  ks_bridge:
    image: elldee/kaspa-stratum-bridge:latest
    container_name: ks_bridge
    restart: unless-stopped
    user: "0"
    command:
      - '-log=true'
      - '-stats=false'
      - '-stratum=:5555'
      - '-prom=:2114'
      - '-kaspa=host.docker.internal:16110'
      - '-mindiff=64'
      - '-vardiff=true'
    ports:
      - "5555:5555"
      - "2114:2114"
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:

