version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: elldeeone-kas-stratum-bridge_1
      APP_PORT: 3000

  ks_bridge:
    image: onemorebsmith/kaspa_bridge:latest
    container_name: ks_bridge
    restart: unless-stopped
    user: "0"
    command:
      - '-log=true'
      - '-stats=false'
      - '-stratum=:5555'
      - '-prom=:2114'
      - '-kaspa=host.docker.internal:16110'
      - '-mindiff=64'
      - '-vardiff=true'
    ports:
      - "5555:5555"
      - "2114:2114"
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:

  
  version: "3.7"

  services:
    app_proxy:
      environment:
        # The format here is: <app-id>_<docker-service-name>_1
        APP_HOST: elldeeone-kas-rusty-node_1
        APP_PORT: 3000

    kaspad:
      container_name: kaspad
      image: supertypo/kaspad:latest
      restart: unless-stopped
      ports:
        - "16110:16110/tcp"
        - "16111:16111/tcp"
      volumes:
        - kaspad:/app/data/

  volumes:
    kaspad:

