version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST:
      APP_PORT:

  node:
    container_name: node
    image: supertypo/kaspad:latest
    restart: unless-stopped
    ports:
      - "16110:16110/tcp"
      - "16111:16111/tcp"
    volumes:
      - kaspad:/app/data/

volumes:
  kaspad:
